connection: &connection
  adapter: postgresql
  encoding: unicode
  database: modelle_development
  pool: 5
  # username: derik
  username: raphael
  host: localhost


development:
  <<: *connection
  database: modelle_development


test:
  <<: *connection
  database: modelle_development

production:
  adapter: postgresql
  url: ENV['DATABASE_URL']
